### ISSUE TITLE
image api

### ISSUE THREAD

**Issue by gitunit** [ros-drivers/leap_motion#15]
any plans to use the image api and therefore publish images?

**Comment by 130s** [comment]
I'm not planning to implement (nor I did know that API. Sounds nice though!) but people are happy to code/run-level  review of someone offers a pull request.

**Comment by gitunit** [comment]
i didn't look close enough - after further reading about this driver, i realised there is already the possibility to use the leap motion as stereo camera.

**Comment by nowittyusername** [comment]
The new wrapper has a node for publishing images from the Leap Motion stereo camera.
