### ISSUE TITLE
Integrate finger bone combinations

### ISSUE THREAD

**Issue by 130s** [ros-drivers/leap_motion#21]
@ph4m I found your work https://github.com/ph4m/leap_motion/commit/932368805a128adf6b50a7a111138662661b5755 and https://github.com/ph4m/leap_motion/commit/8d042130b77fd27111c4184399c38d196cffb2a3
I'm not sure if they are generic enough, but if they're, would you mind opening a pull request?

**Comment by ph4m** [comment]
Sure, doing it now.

**Comment by 130s** [comment]
Addressed by #23.
