### ISSUE TITLE
Improved ROS driver for the Leap Motion gesture sensor

### ISSUE THREAD

**Issue by nowittyusername** [ros-drivers/leap_motion#36]
Hello!

After seeing that the ROS driver for the Leap Motion controller was somewhat lacking I wrote one myself using C++. I would like to know if there's any interest in it here, maybe it could replace the current one.

Currently my ROS package supports one person (left and right arm), publishing raw camera images from the controller, gesture detection, basic visualization using Rviz and a [pointcloud](https://docs.ros.org/api/sensor_msgs/html/msg/PointCloud2.html) generated from a [stereo_image_proc](http://wiki.ros.org/stereo_image_proc) node. The gesture functionality is somewhat untested currently, but I am in the progress of improving it during the coming weeks.

I have also made a filter node implementing a 2nd-order Butterworth lowpass filter that is used to filter the hand's x, y, z coordinates coming from the Leap controller via custom made Human.msg.

I pieced it together from multiple repositories found on Github with main sources of inspiration being the [UTNuclearRobotics](https://github.com/UTNuclearRoboticsPublic/leap_motion_controller), [juancamilog](https://github.com/juancamilog/leap_client) repositories. All other functionality that I deemed missing  was implemented by myself. 

You can find my current work [here](https://github.com/ut-ims-robotics/lmc_ros_driver) for browsing and/or testing the package. If anyone with the right permissions is interested in the merge, let me know.

**Comment by rowsterrr** [comment]
I am currently a research student at my university attempting to do the same sort of thing, obtain the point cloud information in RVIZ. Let me know how you go with this? I have looked at your code but having troubles compiling it unfortunately.

**Comment by warp1337** [comment]
Hey. Just checked your mail. Yes I am open to merge it. We should discuss that first with the ros drivers community.

**Comment by nowittyusername** [comment]
@rowsterrr I replied to your problem in my own  repository.

@warp1337 that's great to hear! I haven't done open-source before so when you say "discuss with the ROS drivers community" does it mean I should do/contact something/someone specific?

**Comment by 130s** [comment]
Sorry for the delayed response.

Replying to [the email thread you opened](https://groups.google.com/d/msgid/ros-sig-drivers/6e9c113c-7448-4dc3-a2a8-33dbc0a3a82b%40googlegroups.com?utm_medium=email&utm_source=footer) here:

>>    For backwards compatibility, have you considered retaining the old driver and adding your new one as an additional node in the same package?
>
> Actually, I hadn't thought about it. However, yes, that is totally possible, easy to do and a good idea.

I agree with @jack-oquin.

In addition, I'm aware of a business entity that uses this package as is. That's just one example, but more than enough reason that we can't just change a released package without backward compatibility.

Possible options I think of:

- (ideal) You add another node to this package.
- (not ideal but better than replacing this package) Rename your package and add it to this repo.

**Comment by warp1337** [comment]
We could also add a new branch, that includes your code?

**Comment by nowittyusername** [comment]
@warp1337 I actually had the same idea. Maybe make a kinetic and forward branches that contain my code and the previous implementation stays where it is, untouched.

**Comment by warp1337** [comment]
Yeah. You should give it a meaningful name, e.g., kinetic-reimplementation ...

**Comment by 130s** [comment]
While branching could be one of the easiest, quickest solutions for developers, I'd have to disagree with that from users point of view. Having multiple branches (I guess that's what you have in mind):
- In ROS ecosystem, I doubt we can make releases to the same ROS distro from the a single repository with different branches (needless to say, binary release is a way to go for users).
- For those who use the pkg from source:
  - you wouldn't be able to use two different branches at the same time (or at least it'd be non-standard way and thus more difficult).
  - Simply confusing unless you really know where things are stored. Needs to be documented somewhere branch agnostic.

So to me disadvantages surpass advantages for branching.

**Comment by warp1337** [comment]
Okay. I see. Then I  suggest to create a new package, i.e, ros_leap_motion_cpp.

**Comment by nowittyusername** [comment]
Very well, I will create a new package then. Thanks for your thoughts, guys!

**Comment by jack-oquin** [comment]
Why a new package? Can't you add the new driver as a separate node in the existing package?

Are there dependency issues which would make that difficult?

**Comment by warp1337** [comment]
I guess the cpp package would pull lot's of deps the python people dont really care about...

Any thoughts?

**Comment by nowittyusername** [comment]
Sorry, might have caused a stir with that last post of mine. What I should have said is that I wouldn't mind the option if it gets there. I didin't see a big reason for having too packages that do the same thing, that's why I contacted you all.

Anyway, if I am to add the driver into the existing package then it will pretty much duplicate what has been aready done, just in a different way. The old code *should* be fine coexisting with mine, but I haven't really tested for any conflicts after I added the its pieces into my own repo.

The only real backwards compatibilty breaking things are (that currently know of) are in the launch files. The If statements are compatible with ROS Kinetic or newer versions (Kinetic is what I use). 

Also, built the driver up as a system of 4 nodes. I have added a quick [sketch ](https://drive.google.com/file/d/1YfPlj2httsYVUq_ICDWrDt56yfa9k9cA/view?usp=sharing)of it so you can have some understanding of the logic behind my work, if you wish. My four nodes are in the circles. 

As for the dependencies, I don't really know what to say about this. Sorry, new at this thing, but you can see my build/exec depends [here](https://github.com/ut-ims-robotics/lmc_ros_driver/blob/18bcc6d739b55554b14c691740fb3292582f5cb1/package.xml#L16-L44).

**Comment by jack-oquin** [comment]
The dependencies don't look all that different at first glance.

Some dependency suggestions:
* Where you have both ``<build_depend>`` and ``<exec_depend>``, just use ``<depend>``.
* Alphabetize the dependencies of each type within that section.
  - That makes it easier to see at a glance what's there and not there.

**Comment by nowittyusername** [comment]
I had the opportunity today to test both packages running from my repository separately and simultaneously. It all went fine and I didn't see that they would be interfering with each others work. Though, skeleton_sender.py has a runtime error somewhere, but that unrelated.

So I would have this clear.The idea is moving towards merging them both into one and marking the old implementation as deprecated? After some time(x months, a year?) the older implementation could be removed.

@jack-oquin Thanks for the suggestion, sometimes it pays to point out the obvious.

**Comment by jack-oquin** [comment]
Quoting from REP-0003:

> If at all possible, maintainers should use a "tick-tock" model where the new APIs are introduced alongside the old (deprecated) APIs, and then remove the old APIs in a subsequent release.

That would take a year or so, which is a reasonable time frame for asking other projects to migrate to your new interface. Good "migration guide" documentation would help considerably.

**Comment by nowittyusername** [comment]
Very well, so if I am to merge my driver with the current implementation the easiest way to do it would be via pull request, no? Just fork it and replace it all with what I have (including the old API).

I know there are special guidelines for doing that (buildfarm, document generation etc) and I will try to familiarize myself with them during the coming weekend/Mon-Wed, however is there something specific I should know about this particular repository. Something I should keep a close eye on?

**Comment by jack-oquin** [comment]
Forking the repo, adding your changes, and then providing a pull request is the preferred update method.

That will trigger the Travis tests, and give the maintainers a good way to review your code. For that purpose, minimizing unnecessary diffs is very helpful.

**Comment by jack-oquin** [comment]
@nowittyusername: Thanks for contributing! :+1:
