### ISSUE TITLE
A question about $ roslaunch leap_motion sensor_sender.launch

### ISSUE THREAD

**Issue by stevensu1838** [ros-drivers/leap_motion#39]
Hi all,

I am new to ROS, and I am trying to use leapmotion to teleoperate a turtlebot. I think my question probabaly will be helpful to other users of your pacakge and thank you all for your great efforts. I've confronting the following questions:

**Firstly**, in INSTALLATION of README.md of this package, it says **git clone https://github.com/warp1337/rosleapmotion.git.**
(which is a different package created by warp 1337 ) 
Doesn't it should be **git clone https://github.com/ros-drivers/leap_motion**?

**Secondly**, I follow one chapter of book _ROS ROBOTICS PROJECTS_ [https://www.safaribooksonline.com/library/view/ros-robotics-projects/9781783554713/] in which your pacages is used. But his steps and commands are different from your instructions in README.md. Especially, he used this command **$ roslaunch leap_motion sensor_sender.launch** in order to recieve the data from leapmotion. But this is not introduced in your README.md. Actually, I did exactly what the book says but this comand doesn't work well. **Can you please kindly tell me where the mistake is if I post the comands in the book ROS ROBOTICS PROJECTS?** Coz the author seems not very responsible to his publications. Thank you so much for all of you!

The following is part of the book I followed:
_1. Installing the ROS driver for the Leap Motion controller_

To interface the Leap Motion with ROS, we will need the ROS driver for it. Here is the link
to get the ROS driver for Leap Motion; you can clone it using the command:
**$ git clone https://github.com/ros-drivers/leap_motion**

Before installing the leap_motion driver package, we have to do a few things to have it
properly compiled. The first step is to set the path of the Leap Motion SDK in the .bashrc file. Assuming thatthe Leap SDK is in the user's home folder with the name LeapSDK , we have to set the path
variable in .bashrc as follows.
**$ export LEAP_SDK=$LEAP_SDK:$HOME/LeapSDK**

This environment variable is needed for compiling the code of the ROS driver, which has
Leap SDK APIs. We also have to add the path of the Python extension of the Leap Motion SDK to .bashrc .
Here is the command used to do it:
**export PYTHONPATH=$PYTHONPATH:$HOME/LeapSDK/lib:$HOME/LeapSDK/lib/x64**

This will enable Leap Motion SDK APIs in Python. After going through the preceding steps,
you can save .bashrc and take a new Terminal, so that we will get the preceding variables
in the new Terminal.
The final step is to copy the libLeap.so file to /usr/local/lib . Here is how we do it:
**$ sudo cp $LEAP_SDK/lib/x64/libLeap.so /usr/local/lib**

After copying, execute ldconfig :
**$ sudo ldconfig**

Okay, you are finished with setting the environment variables. Now you can compile the
leap_motion ROS driver package. You can create a ROS workspace or copy the
leap_motion package to an existing ROS workspace and use catkin_make .
You can use the following command to install the leap_motion package:

**$ catkin_make install --pkg leap_motion**
This will install the leap_motion driver; check whether the ROS workspace path is
properly set.

_2.Testing the Leap Motion ROS driver_
If everything has been installed properly, we can test it using a few commands.
First, launch the Leap Motion driver or control panel using the following command:
**$ sudo LeapControlPanel**
After launching the command, you can verify that the device is working by opening the
Visualizer application. If it's working well, you can launch the ROS driver using the
following command:
**$ roslaunch leap_motion sensor_sender.launch**
If it's working properly, you will get topics with this:
**$ rostopic list**
If you can see rostopic/leapmotion/data in the list, you can confirm that the driver is
working. You can just echo the topic and see that the hand and finger values are coming in,
as shown in the following screenshot:
(That's the end of that chapter)

**Comment by nowittyusername** [comment]
Yes, you should git clone https://github.com/ros-drivers/leap_motion

The command given by the author of the book seems to be correct. It's probaly your setup that's wrong. I can't tell help you more without seeing some error messages. Finally, you can see all the launch files for this package here https://github.com/ros-drivers/leap_motion/tree/hydro/launch
