### ISSUE TITLE
ERROR: Cannot load message class for [leap_motion/leapros]. Are your messages built?

### ISSUE THREAD

**Issue by stevensu1838** [ros-drivers/leap_motion#40]
Hi Sir,

I followed the Read.me instructions and 
After I run command `source  ~catkin_ws/devel/setup.bash && rosrun leap_motion sender.py `I do receive data running on the terminal. 
However, when I try rostopic echo /leapmotion/data, it throws an error: 
```
ysu66@mech1331:~$ rostopic echo /leapmotion/data
ERROR: Cannot load message class for [leap_motion/leapros]. Are your messages built?
```

Can you please show me how to fix it?
Steven

**Comment by nowittyusername** [comment]
If you're doing "rostopic echo /leapmotion/data" from another terminal window you need to source your workspace there as well.

**Comment by enghish** [comment]
> If you're doing "rostopic echo /leapmotion/data" from another terminal window you need to source your workspace there as well.

Thank you so much. This solved my problem
