### ISSUE TITLE
How to convert leapmotion/data to twist like we convert joy to twisit?

### ISSUE THREAD

**Issue by stevensu1838** [ros-drivers/leap_motion#48]
Hi Sir,
I've using a joystick to control a robot arm with the left code very well. However, I'd love to use a LeapMotion to control the arm and I modified the code the the right side code. But it doesn't work. In the rqt_graph the nodes are connected. The robot arm doesn't move as it was control with the joystick.  Can you please show me how I can figure it out??

![image](https://user-images.githubusercontent.com/25648734/49628299-4f4f8180-fa48-11e8-8700-1cd1669b6597.png)
![image](https://user-images.githubusercontent.com/25648734/49628225-d8b28400-fa47-11e8-9c16-98d1681ea9fd.png)
![image](https://user-images.githubusercontent.com/25648734/49628449-1663dc80-fa49-11e8-926a-5928d2a962c5.png)

**Comment by nowittyusername** [comment]
Well you seem to be getting the X,Y,Z coordinates from the _geometry_msgs/Point.msg_. However are you aware that the X,Y,Z in ROS in different from the X,Y,Z used by the Leap Motion? Leap Motion's roll-pitch-yaw is from the perspective of a human. https://developer-archive.leapmotion.com/documentation/v2/python/devguide/Leap_Overview.html

Also by "it doesn't work" what do you mean? Are you even able to get data from the LMC or does the robot arm move weirdely etc.

**Comment by stevensu1838** [comment]
Hi Sir,
First of all, I've learnt the difference between the two coordinates. 
Thank you so much for your attention and support. By saying it doesn't work, I meant to say the robot doesn't move at all. And I am actually able to get data from the LMC. For example, when I run  rostopic echo /leapmotion/data, I get the following data:

![image](https://user-images.githubusercontent.com/25648734/49717272-6d70e800-fcbb-11e8-961e-bac2904a63c1.png)
And you could also see I am receiving the leap data in the rqt graph:
![image](https://user-images.githubusercontent.com/25648734/49717324-98f3d280-fcbb-11e8-8df8-83ce3ef38811.png)

To summarize, I think the reason why I could not control the robot arm as I can with a joystick is as follow:
 form a joystick I actually get data such as  1.1111(when push the stick forward) or - 1.0235(when push the stick forward) from axes 1. Same thing for axes 2, 3, 4 .....
However, 
 from a LMC I receive data like palmpos:  x: 60.1925201416 which probably is not proper to drive the robot.

I've been told it is doable to use the changes in pose between each frame to calculate the movement of the robot arm. 
### like at time 1 I get initial pose palmpos:  x: 60 and at time 2 I read current pose palmpos: x: 80
so change.x between time1 and time2 (In this case, change.x = 80-60 = 20) will be used to give command to the robot. 
 twist.twist.linear.x = msg->change.x*scale_factor

### My question is I receive a large number of data form LMC(as shown in the first pic). In python or C++, how I can set one is initial pose and another one is the current pose? I am a beginner at programming but I do know the basics. Can you please kindly show me how to do it with this great Leapros package?  Thanks a million.

Steven

**Comment by nowittyusername** [comment]
Well the first thing that comes to mind and the easiest way to test it would be to use global variables (most probably not the best in the long run though).
Have 2 global variable like `current_pos `and `previous_pos`. At first they are equal and then you basically do:
```
previous_pos = current_pos
current_pos = new leap_motion data
And here calculate the new difference between the locations
```
https://docs.ros.org/lunar/api/geometry_msgs/html/msg/Pose.html

**Comment by stevensu1838** [comment]
Hi Sir,
Thank you so much for your instructions. I also heard a similar solution form my friend, which is quite close to yours and the only difference is he did prev_val var = current_val at the end of the code snippet 
```
prev_val var = 0
current_val = data

diff = prev - current
prev_val var = current_val
```
Does this matter???

Secondly,  after reading the initial and current reading,  I suppose I need to divide the difference by the seconds it took between these readings. Normally, I think I can calculate the seconds from the publish rate in [leap_motion/scripts/sender.py ](https://github.com/ros-drivers/leap_motion/blob/hydro/scripts/sender.py)
The rate is normally set in the following tow ways in ROS
rate = rospy.Rate(2) in python executables in ROS
or ros::Rate naptime(2) in c++ executables in ROS
However, 
Only the following part is shown in the ` leap_motion/scripts/sender.py` which is related to publish rate. 
```
FREQUENCY_ROSTOPIC_DEFAULT = 0.01
NODENAME = 'leap_pub'
PARAMNAME_FREQ = 'freq'
PARAMNAME_FREQ_ENTIRE = '/' + NODENAME + '/' + PARAMNAME_FREQ
```

        pub_ros.publish(msg)
        rospy.sleep(rospy.get_param(PARAMNAME_FREQ_ENTIRE, FREQUENCY_ROSTOPIC_DEFAULT))
Any idea how I can read or even modify the publish rate of leapros message in this code above?
Thanks with no end!
Steven

**Comment by nowittyusername** [comment]
> ```
> prev_val var = 0
> current_val = data
> 
> diff = prev - current
> prev_val var = current_val
> ```
> Does this matter???

Well in your code you pretty much disregard the previous value by setting it to 0 all the time. Thus your difference will always be -current_value. I don't know if I understood the code snippet correctly but it seems wrong in my opinion.

> ```
> FREQUENCY_ROSTOPIC_DEFAULT = 0.01
> NODENAME = 'leap_pub'
> PARAMNAME_FREQ = 'freq'
> PARAMNAME_FREQ_ENTIRE = '/' + NODENAME + '/' + PARAMNAME_FREQ
>     pub_ros.publish(msg)
>     rospy.sleep(rospy.get_param(PARAMNAME_FREQ_ENTIRE, FREQUENCY_ROSTOPIC_DEFAULT))
> ```
Have a look at these links and try to figure it out.
https://wiki.ros.org/rospy/Overview/Parameter%20Server
https://wiki.ros.org/rospy/Overview/Time#Sleeping_and_Rates
https://github.com/ros-drivers/leap_motion/blob/hydro/launch/sensor_sender.launch

**Comment by stevensu1838** [comment]
Hi Sir,
Thanks a lot for your help. I am getting closer. Will let you know when it is done. Thanks a million

Steven
