### ISSUE TITLE
calculate the change in hand pose from the leap motion tracker by programming

### ISSUE THREAD

**Issue by stevensu1838** [ros-drivers/leap_motion#49]
Hi Sir,
Can you please tell me how I can how I can calculate the change in hand pose from the leap motion tracker by programming? I need to use the change to give a command to drive a robot. Thanks a lot

**Comment by nowittyusername** [comment]
You want to calculate the change in position between to time points? If I understood correctly then just save the X,Y,Z and R.P,Y at `time1` and then calculate the difference at `time2.`

**Comment by stevensu1838** [comment]
Hi Sir,
I feel like it is exactly what I wanna do. But can you please kindly explain more on how to save the X,Y,Z and R.P,Y at time1 in python or C++? I don't find the answer by googling. Thanks a million
