### ISSUE TITLE
Error with sender.py on Melodic

### ISSUE THREAD

**Issue by Moirai** [ros-drivers/leap_motion#53]
Is there anyone who has checked this sourcecode on Melodic?
I have an error with sender.py ;
~~~
c@C:~$ export PYTHONPATH=$PYTHONPATH:$HOME/LeapSDK/lib:$HOME/LeapSDK/lib/x64
c@C:~$ rosrun leap_motion sender.py 
Traceback (most recent call last):
  File "/home/camellia/Testing_melodic/src/leap_motion/scripts/sender.py", line 12, in <module>
    from leap_motion.msg import leap
ImportError: No module named msg
~~~
Installed with its soucecode on Kinetic is OK.

Please tell me if you have tips.
Thanks in advance for your help.

**Comment by nowittyusername** [comment]
DISCLAIMER: The .py implementation is deprecated and I don't plan to support it in the future.
It complains about msg files not being present. Have you tried sourcing the setup.bash?

**Comment by Moirai** [comment]
> Have you tried sourcing the setup.bash?

yes. I wrote it on .bashrc.

**Comment by nowittyusername** [comment]
> > Have you tried sourcing the setup.bash?
> 
> yes. I wrote it on .bashrc.

You need to do it every time when you open a new terminal.  

leap_ws$ source devel/setup.bash
leap_ws$ rosrun leap_motion sender.py  // Be sure to have roscore running!

I don't have the LMC with me at the moment, but running the code seems to work on my machine.

**Comment by Moirai** [comment]
I tried it once more, but didn't work. 
~~~
camellia@Camellia:~$ roscd
camellia@Camellia:~/Testing_melodic/devel$ cd -
/home/camellia
camellia@Camellia:~$ export PYTHONPATH=$PYTHONPATH:$HOME/LeapSDK/lib:$HOME/LeapSDK/lib/x64
camellia@Camellia:~$ rosrun leap_motion sender.py
Traceback (most recent call last):
  File "/home/camellia/Testing_melodic/src/leap_motion/scripts/sender.py", line 12, in <module>
    from leap_motion.msg import leap
ImportError: No module named msg
camellia@Camellia:~$ 
~~~
I have a leap motion device and checked it on Kinetic is OK, but it doesn't work on Melodic.
I don't understand why...

**Comment by nowittyusername** [comment]
Does this point to the correct folder? 
`export PYTHONPATH=$PYTHONPATH:$HOME/LeapSDK/lib:$HOME/LeapSDK/lib/x64`

Also I do something like this:

```
1. open terminal
2. roscore
```

```
1. open ANOTHER terminal
2. cd leap_ws
3. source devel/setup.bash
4. export PYTHONPATH=$PYTHONPATH:~/SOMETHING/SOMETHING/leap_motion/LeapSDK/lib:~~/SOMETHING/SOMETHING/leap_motion/LeapSDK/lib/x64
5. rosrun leap_motion sender.py

```
When I do these steps I get "Initialized Leap Motion Device" as a response.

**Comment by Moirai** [comment]
> Does this point to the correct folder?
export PYTHONPATH=$PYTHONPATH:$HOME/LeapSDK/lib:$HOME/LeapSDK/lib/x64

yes, I put LeapSDK/ on home directly.
~~~
camellia@Camellia:~$ ls 
Desktop    Downloads         LeapSDK  Pictures  snap       Testing_melodic  Workshop
Documents  examples.desktop  Music    Public    Templates  Videos
~~~

ROS knows leap and leapros.
~~~
camellia@Camellia:~$ rosmsg list | grep leap
leap_motion/Bone
leap_motion/Finger
leap_motion/Gesture
leap_motion/Hand
leap_motion/Human
leap_motion/leap
leap_motion/leapros
~~~

I tried it once more, but same error again.
~~~
camellia@Camellia:~$ rostopic list
/rosout
/rosout_agg
camellia@Camellia:~$ roscd
camellia@Camellia:~/Testing_melodic/devel$ cd -
/home/camellia
camellia@Camellia:~$ export PYTHONPATH=$PYTHONPATH:$HOME/LeapSDK/lib:$HOME/LeapSDK/lib/x64
camellia@Camellia:~$ rosrun leap_motion sender.py 
Traceback (most recent call last):
  File "/home/camellia/Testing_melodic/src/leap_motion/scripts/sender.py", line 12, in <module>
    from leap_motion.msg import leap
ImportError: No module named msg
~~~

**Comment by nowittyusername** [comment]
Try cloning my git repo again. 
Basically it's a problem with message generation when you do "catkin_make".  Just to be 100% sure do a catkin_make clean, check the package.xml and CMakeLists.txt.

https://github.com/ros-drivers/leap_motion/blob/f9defaef361f7a95d30a969b08bddf3ad4b6dc85/CMakeLists.txt#L44-L45

https://github.com/ros-drivers/leap_motion/blob/f9defaef361f7a95d30a969b08bddf3ad4b6dc85/package.xml#L29-L30

http://www.theconstructsim.com/solve-error-importerror-no-module-named-xxxx-msg-2/

**Comment by Moirai** [comment]
Thank you @nowittyusername , I did it! (but I didn't understand why, I guess "catkin_make clean" what I needed).
I did get the sourcecode from repository again, catkin_make clean and catkin_make.
Just to be sure, I replaced LeapSDK/ in the leap_motion package with a newest Leapmotion driver's in my environment, ver.2.3. 

So, would you like to release leap_motion on Melodic for getting apt install it ?

**Comment by nowittyusername** [comment]
That's the eventual plan, but I am not familiar enough with the ROS buildfarm to do a proper release. See issue #47

**Comment by Moirai** [comment]
I see.
I don't mind in particular listner_param.yaml , because I don't use visualization.launch and demo.launch. 
I'm waiting for its official release on Melodic.
Please let me know if there is anything I can do.

Thanks you very much for your support.

**Comment by TejasPhutane** [comment]
Try using " catkin_make install " , it solved this error ,no need to source again in terminal,running successfully in ros melodic
