### ISSUE TITLE
roslaunch problem

### ISSUE THREAD

**Issue by lorenzosteccanella** [ros-drivers/leap_motion#9]
while running the roslaunch command we encounter the following errors: 

ERROR: cannot launch node of type [leap_motion/leap_camera]: leap_motion
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/opt/ros/indigo/share
ROS path [2]=/opt/ros/indigo/stacks
ERROR: cannot launch node of type [leap_motion/leap_hands]: leap_motion
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/opt/ros/indigo/share
ROS path [2]=/opt/ros/indigo/stacks

do you have any suggestions for these problems?

**Comment by 130s** [comment]
Hopefully [Indigo DEB will soon become available](https://github.com/ros/rosdistro/pull/7364). You can test with it.
And again please provide more info.

**Comment by Squelsh** [comment]
I assume your execuatables were simply not built as there is a bug in the CMake file.
This is corrected in my Merge Request.
